defmodule EventDefinitionManagement.Repo.Migrations.CreateResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:organization_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :custom_name, :text
      add :enabled, :boolean, default: true
      add :settings, :map, default: %{}
      add :global_event_id, :uuid, null: false
    end

    create table(:global_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:organization_configs) do
      modify :global_event_id,
             references(:global_events,
               column: :id,
               name: "organization_configs_global_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:global_events) do
      add :name, :text, null: false
      add :code, :text, null: false
      add :description, :text
    end

    create unique_index(:global_events, [:code], name: "global_events_unique_code_index")
  end

  def down do
    drop_if_exists unique_index(:global_events, [:code], name: "global_events_unique_code_index")

    alter table(:global_events) do
      remove :description
      remove :code
      remove :name
    end

    drop constraint(:organization_configs, "organization_configs_global_event_id_fkey")

    alter table(:organization_configs) do
      modify :global_event_id, :uuid
    end

    drop table(:global_events)

    drop table(:organization_configs)
  end
end
