defmodule EventDefinitionManagement.Repo.Migrations.AddNewResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :role, :text, null: false, default: "operator"
    end

    create table(:organization_event_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :custom_name, :text
      add :active, :boolean, default: true
      add :parameters, :map, default: %{}
      add :actions, :map, default: %{}

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "organization_event_configs_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :global_event_definition_id, :uuid, null: false
    end

    create table(:global_event_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:organization_event_configs) do
      modify :global_event_definition_id,
             references(:global_event_definitions,
               column: :id,
               name: "organization_event_configs_global_event_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:global_event_definitions) do
      add :name, :text, null: false
      add :description, :text
      add :event_type, :text, null: false
      add :default_parameters, :map, default: %{}
      add :version, :bigint, default: 1
      add :active_globally, :boolean, default: false
      add :status, :text, default: "en_attente"
    end

    create unique_index(:global_event_definitions, [:name],
             name: "global_event_definitions_unique_name_index"
           )

    create table(:alerts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :message, :text
      add :vehicle_id, :text
      add :vehicle_immat, :text
      add :latitude, :float
      add :longitude, :float
      add :speed, :float
      add :fuel_level, :float
      add :status, :text, default: "en_attente"
      add :acknowledged_at, :utc_datetime_usec
      add :acknowledged_by, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "alerts_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_event_config_id,
          references(:organization_event_configs,
            column: :id,
            name: "alerts_organization_event_config_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :global_event_definition_id,
          references(:global_event_definitions,
            column: :id,
            name: "alerts_global_event_definition_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:alerts, "alerts_organization_id_fkey")

    drop constraint(:alerts, "alerts_organization_event_config_id_fkey")

    drop constraint(:alerts, "alerts_global_event_definition_id_fkey")

    drop table(:alerts)

    drop_if_exists unique_index(:global_event_definitions, [:name],
                     name: "global_event_definitions_unique_name_index"
                   )

    alter table(:global_event_definitions) do
      remove :status
      remove :active_globally
      remove :version
      remove :default_parameters
      remove :event_type
      remove :description
      remove :name
    end

    drop constraint(
           :organization_event_configs,
           "organization_event_configs_global_event_definition_id_fkey"
         )

    alter table(:organization_event_configs) do
      modify :global_event_definition_id, :uuid
    end

    drop table(:global_event_definitions)

    drop constraint(
           :organization_event_configs,
           "organization_event_configs_organization_id_fkey"
         )

    drop table(:organization_event_configs)

    alter table(:users) do
      modify :role, :text, null: true, default: "client_admin"
    end
  end
end
