defmodule EventDefinitionManagement.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :confirmed_at
      modify :role, :text, default: "client_admin"
    end
  end

  def down do
    alter table(:users) do
      modify :role, :text, default: "operator"
      add :confirmed_at, :utc_datetime_usec
    end
  end
end
