defmodule EventDefinitionManagement.Repo.Migrations.CompleteRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organization_configs) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "organization_configs_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:organization_configs, "organization_configs_organization_id_fkey")

    alter table(:organization_configs) do
      remove :organization_id
    end
  end
end
